apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "daemon-cronjob.fullname" . }}-controller-manager
  labels:
  {{- include "daemon-cronjob.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
